name: analytics
description: This package provides analytics/crashlytics services and widgets

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../../packages/common

  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  custom_lint: any
