name: marvelapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: 5.0.3
  dartz: 0.10.1
  mobx: 2.1.1
  dio: 4.0.6
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_svg: 1.1.5
  flutter_mobx: 2.0.6+4
  equatable: 2.0.3
  crypto: 3.0.2
  cupertino_icons: 1.0.2

dev_dependencies:
  build_runner: 2.1.5
  mobx_codegen: 2.0.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
          weight: 300

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 200
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
