name: marvel_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  flutter: ">=3.22.2 <4.0.0"
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_native_splash: ^2.4.0

  # Networking
  dio: ^5.4.3
  talker_dio_logger: ^4.3.2
  cached_network_image: ^3.3.1

  # Firebase
  firebase_crashlytics: ^3.5.7
  firebase_core: ^2.32.0

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # CACHE
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#FF4141"
  image: assets/images/iron-man.png
  ios: true
  web: false
  android: true
  android_12:
    color: "#FF4141"
    image: assets/images/iron-man.png