name: mottu_http
description: This package provides HTTP services for Mottu apps

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  common:
    path: ../common
  persistence:
    path: ../persistence

  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  custom_lint: any
  mocktail: ^1.0.3
