name: mottu_design_system
description: This package provides design system components, such as themes (colors, fonts etc) and reusable components. It follows the Atomic Design pattern.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  custom_lint: any

flutter:
  fonts:
    - family: Bangers
      fonts:
        - asset: packages/mottu_design_system/assets/fonts/Bangers-Regular.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: packages/mottu_design_system/assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: packages/mottu_design_system/assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: packages/mottu_design_system/assets/fonts/Roboto-Regular.ttf
          weight: 400
