name: mottu_design_system
description: This package provides design system components, such as themes (colors, fonts etc) and reusable components. It follows the Atomic Design pattern.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  custom_lint: any
