name: common
description: Every library and components that are common to different packages and apps for the Mottur project.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  package_info_plus: ^8.0.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: any
  custom_lint: any
