name: persistence
description: This package provides essential services for storing data - e.g. complex cache data

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  analytics:
    path: ../analytics
  common:
    path: ../common

  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  custom_lint: any
  mocktail: ^1.0.3
  hive_test: ^1.0.0
